# Generated by Django 2.2.1 on 2019-12-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20191209_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=50)),
                ('repo_url', models.CharField(max_length=100)),
                ('repo_dec', models.TextField(max_length=200)),
            ],
        ),
    ]
